core: Update to commit 091e960.
https://github.com/mupen64plus/mupen64plus-core/commit/091e960

* 091e960 update FSF address in license
*   cd69499 Merge pull request #526 from bsmiles32/fix_binutils_2_29
|\
| * 0bfe65b Fix undefined reference to print_insn_i386 with libopcode >= 2.29
|/
* 97631d7 remove OSX-specific code from osal/files_unix.c, and when looking for shared files in files_macos.c, don't use the bundle Resources directory unless the file is actually there
* 3ea3f6e update osx bundle generation script to put things in more usual locations for macos
*   99029c8 Merge pull request #521 from bsmiles32/fix_empty_dynarec
|\
| * 225b52d Fix free_all_registers prototype.
| * bc8f937 Fix init_cache prototype.
|/
*   4fcd4ee Merge pull request #519 from bsmiles32/less_g_dev
|\
| *   73a8e37 Merge branch 'master' into less_g_dev
| |\
| |/
|/|
* |   82b9e51 Merge pull request #513 from bsmiles32/sidmaduration
|\ \
| * | 4d1b55a Add SiDmaDuration option.
| | * 5d4e054 Move g_dev usage inside savestate instead of interrupt module.
| | * 8d22be2 Avoid usage of g_dev in savesate module.
| | * c2dd188 Avoid global variable ROM_PARAM in cheat module.
| | * 4d02e86 Cleanup header inclusions in cheat module.
| | * 4dbbf62 Avoid usage of g_dev inside cheat module.
| | * b6e7c26 Move cheat state inside a struct.
| | * 5d184fb Prefer forward declaration to header inclusion.
| | * f714f13 Rename header guard in cheat.h
| | * 2a30f6f Formatting cleanups in cheat module.
| | * 67fc6e6 Forgot to rmeove dbg_types from Visual Studio files.
| | * 69fe319 Formattings cleanup.
| | * 43bef9d Avoid usage of g_dev in debugger modules. Use standard fixed-size types.
| | * 1b4f065 Avoid usage of g_dev inside dbg_memory module.
| | * b7e99db Avoid usage of g_dev in most dynrec functions.
| |/
|/|
* |   004a82e Merge pull request #515 from bsmiles32/arm_compile_fix
|\ \
| * | f155526 Fix compilation of new dynarec.
| |/
* |   865a184 Merge pull request #514 from loganmc10/crashfix3
|\ \
| |/
|/|
| * bcd2b01 Fix potential crash with FBInfo and save states
|/
*   0078d54 Merge pull request #510 from bsmiles32/cleanings
|\
| * e59aa29 Reindent dynarec properly.
| * 7be9097 Make fpu modes internal to dynarec.c files
| * 60fb63c Expose less dynarec internal headers
| * 80915c1 Move dynarec_setup_code to recomp module.
| * 3e2e24c Remove unneeded headers
| * d95edb6 Cosmetic changes to virtual_to_physical function.
| * d8478af Fix dynarec_setup_code unused function warning with NEW_DYNAREC
| * 20ba423 Remove unneeded headers in tlb module.
| * 908a273 Move exception code into cp0 module.
| * 9b5e185 clock_backend_interface forward declaration comes from mbc3_rtc header.
| * 5d1c5ce Prefer forward declaration to header inclusion in gb_cart header.
| * 64c114c Remove unneeded declaration and header.
| * 4b848e2 Add missing forward declaration
| * 03496df Replace sl macro with tohl/fromhl macros
| * a7cd948 Add missing forward declaration.
| * 5e9301e Remove unused header.
|/
*   3004e80 Merge pull request #494 from StenApp/patch-2
|\
| * b8bef34 Update Makefile
| * abdee55 Update Makefile
| * a28eebe Update Makefile
* fb274ac bugs
* 88043b6 moved files_macos.c to correct location
*   3525351 Merge pull request #495 from StenApp/patch-1
|\
| * 1f61d7e Update files_macos.c
| * 0a00cc0 Update files_macos.c
| * efcb812 Update files_macos.c
| * 5f16945 Update files_macos.c
| * 93482af Update files_macos.c
| * 00e7d54 Create files_macos.c
*   5fb51e8 Merge pull request #507 from bentley/master
|\
| * 934a72c Update homepage.
| * 4d6ad6b Update wiki links.
| * e7ffde1 Update link to bug tracker.
* d7cb245 Merge pull request #505 from loganmc10/xxh
* 6f0ca6c Update xxHash to 0.6.4