bugfix: Fix AudioTrack IllegalStateException.
Not quite sure how to replicate this bug but I see a lot of it in the
crash reports:

 java.lang.IllegalStateException: play() called on uninitialized AudioTrack.
 at android.media.AudioTrack.play(AudioTrack.java:883)
 at paulscode.android.mupen64plusae.CoreInterfaceNative$1.run(CoreInterfaceNative.java:356)

I think the bug is related to an existing audio track not quitting
before initializing a new one.  If I am correct, then the bug was
introduced in commit 6cfff95c269a3aad48a138d1cd5fcb81e383b4b9, where
some SDL2 example code was cut & pasted into the app overtop one of our
previous bugfixes.

To (hopefully) fix the bug, I just reverted the code to what it was
prior to commit 6cfff95c269a3aad48a138d1cd5fcb81e383b4b9 (with a few
minor changes).