core: Update to commit fba49e3.
https://github.com/Gillou68310/mupen64plus-core/commit/fba49e3

* fba49e3 Add synchronization event between RSP and CPU
* 091e960 update FSF address in license
*   cd69499 Merge pull request #526 from bsmiles32/fix_binutils_2_29
|\
| * 0bfe65b Fix undefined reference to print_insn_i386 with libopcode >= 2.29
|/
* 97631d7 remove OSX-specific code from osal/files_unix.c, and when looking for shared files in files_macos.c, don't use the bundle Resources directory unless the file is actually there
* 3ea3f6e update osx bundle generation script to put things in more usual locations for macos
*   99029c8 Merge pull request #521 from bsmiles32/fix_empty_dynarec
|\
| * 225b52d Fix free_all_registers prototype.
| * bc8f937 Fix init_cache prototype.
|/
*   4fcd4ee Merge pull request #519 from bsmiles32/less_g_dev
|\
| *   73a8e37 Merge branch 'master' into less_g_dev
| |\
| |/
|/|
* | 82b9e51 Merge pull request #513 from bsmiles32/sidmaduration
* | 4d1b55a Add SiDmaDuration option.
 /
* 5d4e054 Move g_dev usage inside savestate instead of interrupt module.
* 8d22be2 Avoid usage of g_dev in savesate module.
* c2dd188 Avoid global variable ROM_PARAM in cheat module.
* 4d02e86 Cleanup header inclusions in cheat module.
* 4dbbf62 Avoid usage of g_dev inside cheat module.
* b6e7c26 Move cheat state inside a struct.
* 5d184fb Prefer forward declaration to header inclusion.
* f714f13 Rename header guard in cheat.h
* 2a30f6f Formatting cleanups in cheat module.
* 67fc6e6 Forgot to rmeove dbg_types from Visual Studio files.
* 69fe319 Formattings cleanup.
* 43bef9d Avoid usage of g_dev in debugger modules. Use standard fixed-size types.
* 1b4f065 Avoid usage of g_dev inside dbg_memory module.
* b7e99db Avoid usage of g_dev in most dynrec functions.